In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import re

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style("white")
%matplotlib inline

In [2]:
yearly=pd.read_pickle('yearly.pkl')

In [3]:
for col in yearly.columns:
    print(col)

id
first_gift_year
lapsed_count
recovered_count
max_consec_giving_years
total_giving_years
count_2013
count_2014
count_2015
count_2016
count_2017
count_yr0_x
count_yr1_x
count_yr2_x
count_yr3_x
count_yr4_x
lapsed_amount
recovered_amount
amount_2013
amount_2014
amount_2015
amount_2016
amount_2017
lapsed_amount_2013
lapsed_amount_2014
lapsed_amount_2015
lapsed_amount_2016
lapsed_amount_2017
upgraded_amount_2013
upgraded_amount_2014
upgraded_amount_2015
upgraded_amount_2016
upgraded_amount_2017
downgraded_amount_2013
downgraded_amount_2014
downgraded_amount_2015
downgraded_amount_2016
downgraded_amount_2017
amount_yr0
amount_yr1
amount_yr2
amount_yr3
amount_yr4
count_yr0_y
count_yr1_y
count_yr2_y
count_yr3_y
count_yr4_y
lapsed_amount_yr0
lapsed_amount_yr1
lapsed_amount_yr2
lapsed_amount_yr3
lapsed_amount_yr4
upgraded_amount_yr0
upgraded_amount_yr1
upgraded_amount_yr2
upgraded_amount_yr3
upgraded_amount_yr4
downgraded_amount_yr0
downgraded_amount_yr1
downgraded_amount_yr2
downgraded_amount_yr3
downgraded_amount_yr4
amount_01_2013
amount_02_2013
amount_03_2013
amount_04_2013
amount_05_2013
amount_06_2013
amount_07_2013
amount_08_2013
amount_09_2013
amount_10_2013
amount_11_2013
amount_12_2013
amount_01_2014
amount_02_2014
amount_03_2014
amount_04_2014
amount_05_2014
amount_06_2014
amount_07_2014
amount_08_2014
amount_09_2014
amount_10_2014
amount_11_2014
amount_12_2014
amount_01_2015
amount_02_2015
amount_03_2015
amount_04_2015
amount_05_2015
amount_06_2015
amount_07_2015
amount_08_2015
amount_09_2015
amount_10_2015
amount_11_2015
amount_12_2015
amount_01_2016
amount_02_2016
amount_03_2016
amount_04_2016
amount_05_2016
amount_06_2016
amount_07_2016
amount_08_2016
amount_09_2016
amount_10_2016
amount_11_2016
amount_12_2016
amount_01_2017
amount_02_2017
amount_03_2017
amount_04_2017
amount_05_2017
amount_06_2017
amount_07_2017
amount_08_2017
amount_09_2017
amount_10_2017
amount_11_2017
amount_12_2017
amount_total
count_total
amount_01_yr0
amount_02_yr0
amount_03_yr0
amount_04_yr0
amount_05_yr0
amount_06_yr0
amount_07_yr0
amount_08_yr0
amount_09_yr0
amount_10_yr0
amount_11_yr0
amount_12_yr0
amount_01_yr1
amount_02_yr1
amount_03_yr1
amount_04_yr1
amount_05_yr1
amount_06_yr1
amount_07_yr1
amount_08_yr1
amount_09_yr1
amount_10_yr1
amount_11_yr1
amount_12_yr1
amount_01_yr2
amount_02_yr2
amount_03_yr2
amount_04_yr2
amount_05_yr2
amount_06_yr2
amount_07_yr2
amount_08_yr2
amount_09_yr2
amount_10_yr2
amount_11_yr2
amount_12_yr2
amount_01_yr3
amount_02_yr3
amount_03_yr3
amount_04_yr3
amount_05_yr3
amount_06_yr3
amount_07_yr3
amount_08_yr3
amount_09_yr3
amount_10_yr3
amount_11_yr3
amount_12_yr3
amount_01_yr4
amount_02_yr4
amount_03_yr4
amount_04_yr4
amount_05_yr4
amount_06_yr4
amount_07_yr4
amount_08_yr4
amount_09_yr4
amount_10_yr4
amount_11_yr4
amount_12_yr4
years_donated
perc_years_donated
gift_pattern
donor_profile
behavior_2013
behavior_2014
behavior_2015
behavior_2016
behavior_2017
gainloss_2013
gainloss_2014
gainloss_2015
gainloss_2016
gainloss_2017
gainloss_2014_amt
gainloss_2015_amt
gainloss_2016_amt
gainloss_2017_amt

In [6]:
yearly.head()

,id,first_gift_year,lapsed_count,recovered_count,max_consec_giving_years,total_giving_years,count_2013,count_2014,count_2015,count_2016,...,behavior_2017,gainloss_2013,gainloss_2014,gainloss_2015,gainloss_2016,gainloss_2017,gainloss_2014_amt,gainloss_2015_amt,gainloss_2016_amt,gainloss_2017_amt
1,4aaab6d244bf3599682239ed5591af8a,2016-01-01,2,1,1,1,0,0,0,1,...,lapse_new,none,none,none,gain,loss,0.0,0.0,25.0,-25.0
3,377944ad61f72d800b25ec1862aec363,2016-01-01,2,1,1,1,0,0,0,1,...,lapse_new,none,none,none,gain,loss,0.0,0.0,25.0,-25.0
4,6d5b22d39e68c656071a842732c63a0c,2015-01-01,4,3,2,3,0,0,1,1,...,lapse_repeat,none,none,gain,loss,loss,0.0,70.0,-45.0,-25.0
5,896c75c9b8d9a91c759746e566cd3f37,2016-01-01,2,1,1,1,0,0,0,1,...,lapse_new,none,none,none,gain,loss,0.0,0.0,15.0,-15.0
6,8a1875762c85932fff192ea126ccdff2,2013-01-01,2,1,1,1,1,0,0,0,...,none,gain,loss,none,none,none,-50.0,0.0,0.0,0.0

In [5]:
yearly.groupby('first_gift_year')

In [17]:
y15=yearly.query('first_gift_year == "2015-01-01"')

In [18]:
y15.id.count()

290390

In [21]:
y15.behavior_2017.value_counts()

none            259457
lapse_repeat     18008
recover           9764
maintain          1116
downgrade         1031
upgrade           1014
Name: behavior_2017, dtype: int64

In [22]:
y15.query('behavior_2017 == "lapse_repeat"')

,id,first_gift_year,lapsed_count,recovered_count,max_consec_giving_years,total_giving_years,count_2013,count_2014,count_2015,count_2016,...,behavior_2017,gainloss_2013,gainloss_2014,gainloss_2015,gainloss_2016,gainloss_2017,gainloss_2014_amt,gainloss_2015_amt,gainloss_2016_amt,gainloss_2017_amt
4,6d5b22d39e68c656071a842732c63a0c,2015-01-01,4,3,2,3,0,0,1,1,...,lapse_repeat,none,none,gain,loss,loss,0.0,70.0,-45.00,-25.00
63,ef92ae325590784d7a8141ce8db88f79,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,loss,loss,0.0,200.0,-36.37,-163.63
84,af0b1d12c4e9deac4fcd85a5186c9b08,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,gain,loss,0.0,25.0,25.00,-50.00
236,a44cd2afe425a0f93cc8c707c4042c20,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,gain,loss,0.0,25.0,15.00,-40.00
245,8e7e3a4dc1553b6c9064890de2c447f4,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,none,loss,0.0,25.0,0.00,-25.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2010796,f993aa285a8676cfd6674425f22117a0,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,loss,loss,0.0,25.0,-5.00,-20.00
2011278,8957973c26d1d82f87a4491c77dfe31e,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,gain,loss,0.0,25.0,75.00,-100.00
2011279,86ae22dcfb834990f90acb1e8cbb31fe,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,none,loss,0.0,100.0,0.00,-100.00
2011558,77d3f1a6fc18fbb72062ac8a752901ae,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,gain,loss,0.0,10.0,190.00,-200.00
2012668,96815da190731f2fe644b976dea21ffa,2015-01-01,3,2,2,2,0,0,1,1,...,lapse_repeat,none,none,gain,gain,loss,0.0,10.0,211.40,-221.40

In [23]:
yearly2=yearly[['id',
'first_gift_year',
'years_donated',
'perc_years_donated',
'gift_pattern',
'donor_profile',
'behavior_2013',
'behavior_2014',
'behavior_2015',
'behavior_2016',
'behavior_2017',
'gainloss_2013',
'gainloss_2014',
'gainloss_2015',
'gainloss_2016',
'gainloss_2017',
'gainloss_2014_amt',
'gainloss_2015_amt',
'gainloss_2016_amt',
'gainloss_2017_amt']].copy()

In [31]:
y13=yearly2.query('first_gift_year=="2013-01-01"')

In [32]:
y13

,id,first_gift_year,years_donated,perc_years_donated,gift_pattern,donor_profile,behavior_2013,behavior_2014,behavior_2015,behavior_2016,behavior_2017,gainloss_2013,gainloss_2014,gainloss_2015,gainloss_2016,gainloss_2017,gainloss_2014_amt,gainloss_2015_amt,gainloss_2016_amt,gainloss_2017_amt
6,8a1875762c85932fff192ea126ccdff2,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-50.00,0.0,0.0,0.0
7,a3f070e439d52de72ca62dc41f9b16a4,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-50.00,0.0,0.0,0.0
10,391f14831940fc7bc41df2cd7fb06030,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-100.00,0.0,0.0,0.0
11,531ed26f1a505282337e0d805be97281,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-25.00,0.0,0.0,0.0
80,5aa3b838e69e2c69bec20c2694d15e80,2013-01-01,2.0,0.4,"1,3,",repeat,new,lapse_new,recover,lapse_repeat,none,gain,loss,gain,loss,none,-25.00,10.0,-10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024511,a2cea722f139435f58189b1418775d9e,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-50.00,0.0,0.0,0.0
2024512,d7ee646ade3cf2b2b97341b3f4021e26,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-25.00,0.0,0.0,0.0
2024513,d5eaced55b056522a87a9e6f0fc32a64,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-25.00,0.0,0.0,0.0
2024518,59956132226233b39293b709e98e589b,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-50.00,0.0,0.0,0.0
2024541,9b260707ec97a87dc2073e9b5e958005,2013-01-01,1.0,0.2,"1,",one_time,new,lapse_new,none,none,none,gain,loss,none,none,none,-343.21,0.0,0.0,0.0

In [47]:
print(y16.behavior_2013.value_counts())
print(y16.behavior_2014.value_counts())
print(y16.behavior_2015.value_counts())
print(y16.behavior_2016.value_counts())
print(y16.behavior_2017.value_counts())

none    368953
Name: behavior_2013, dtype: int64
none    368953
Name: behavior_2014, dtype: int64
none    368953
Name: behavior_2015, dtype: int64
new    368953
Name: behavior_2016, dtype: int64
lapse_new    342960
downgrade      9195
maintain       8833
upgrade        7965
Name: behavior_2017, dtype: int64

In [39]:
y13.query('behavior_2017 == "lapse_repeat"')

,id,first_gift_year,years_donated,perc_years_donated,gift_pattern,donor_profile,behavior_2013,behavior_2014,behavior_2015,behavior_2016,behavior_2017,gainloss_2013,gainloss_2014,gainloss_2015,gainloss_2016,gainloss_2017,gainloss_2014_amt,gainloss_2015_amt,gainloss_2016_amt,gainloss_2017_amt
237,9484c658cbd6aae5f7c74f01e654513e,2013-01-01,3.0,0.6,"1,3,4,",repeat,new,lapse_new,recover,upgrade,lapse_repeat,gain,loss,gain,gain,loss,-53.5,25.0,25.00,-50.00
748,aae928541c489fa7055f0dd22961f819,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-50.0,0.0,50.00,-50.00
1256,f3c474dc62d187529db7f24ac56ee3e5,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-100.0,0.0,121.74,-121.74
1751,771f29adf1510aab911829bd77e8d471,2013-01-01,3.0,0.6,"1,2,4,",repeat,new,downgrade,lapse_repeat,recover,lapse_repeat,gain,loss,loss,gain,loss,-20.0,-10.0,50.00,-50.00
1925,2cdd2e4f691e42720548487df340061c,2013-01-01,3.0,0.6,"1,3,4,",repeat,new,lapse_new,recover,downgrade,lapse_repeat,gain,loss,gain,loss,loss,-100.0,200.0,-101.00,-99.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947774,f5f1953521c5fe2d962dfe451a19a120,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-25.0,0.0,15.00,-15.00
1971279,0d691a2e2769fb75be06aced550bf349,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-100.0,0.0,99.00,-99.00
1979728,837674def1b3ab395812512060dda3c0,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-25.0,0.0,50.00,-50.00
1986234,6a23a2fad8f3332a974d4b555de62bf9,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-50.0,0.0,40.00,-40.00
2019881,25241b80ae5fd3c421a119ddb1c0c7c9,2013-01-01,2.0,0.4,"1,4,",repeat,new,lapse_new,none,recover,lapse_repeat,gain,loss,none,gain,loss,-50.0,0.0,50.00,-50.00

In [48]:
donations_13to17=pd.read_pickle('donations_13to17.pkl')

In [55]:
d13=donations_13to17.query('first_gift_year=="2013-01-01"')
d14=donations_13to17.query('first_gift_year=="2014-01-01"')
d15=donations_13to17.query('first_gift_year=="2015-01-01"')
d16=donations_13to17.query('first_gift_year=="2016-01-01"')
d17=donations_13to17.query('first_gift_year=="2017-01-01"')

In [59]:
print(d16.groupby('behavior_2013').count()['id'])
print(d16.groupby('behavior_2014').count()['id'])
print(d16.groupby('behavior_2015').count()['id'])
print(d16.groupby('behavior_2016').count()['id'])
print(d17.groupby('behavior_2017').count()['id'])

behavior_2013
none    445598
Name: id, dtype: int64
behavior_2014
none    445598
Name: id, dtype: int64
behavior_2015
none    445598
Name: id, dtype: int64
behavior_2016
new    445598
Name: id, dtype: int64
behavior_2017
new    434991
Name: id, dtype: int64